"""Authentication for /api/lint.

Three modes, picked by which env vars are set:

- **Clerk JWT** (set CLERK_SECRET_KEY). The dependency verifies the Bearer
  token against Clerk's JWKS and returns the Clerk `user_id` from the JWT's
  `sub` claim. Production path.
- **Static bearer** (set SHARPER_API_TOKEN). Pre-shared token, constant-time
  comparison. Returns "shared-token" as the user_id placeholder. Useful for
  service-to-service calls and as a back-compat path while the frontend
  hasn't yet migrated to Clerk session tokens.
- **Both set (recommended for now)**: Clerk is tried first. If the request
  doesn't carry a JWT-shaped bearer or Clerk verification fails, falls back
  to the static-bearer check. This is the safe migration path: existing
  callers using SHARPER_API_TOKEN keep working while new Clerk-signed
  requests are accepted.

If neither is set, requests pass through as "anonymous-dev" -- only safe on
loopback. `api.run()` refuses to bind to a non-loopback host when neither
is configured.

Authorized parties (Clerk):
    CLERK_AUTHORIZED_PARTIES is a comma-separated list of origins that may
    issue Clerk session tokens for us. Set this to your Vercel deploy URL +
    localhost dev origin. If unset, Clerk skips the authorized-party check
    (only recommended in dev).
"""

from __future__ import annotations

import logging
import os
import secrets
from typing import Optional

from fastapi import Header, HTTPException, Request, status

logger = logging.getLogger(__name__)


# ----- Env-var helpers -------------------------------------------------------


def _clerk_secret() -> Optional[str]:
    val = os.getenv("CLERK_SECRET_KEY", "").strip()
    return val or None


def _expected_static_token() -> Optional[str]:
    val = os.getenv("SHARPER_API_TOKEN", "").strip()
    return val or None


def _authorized_parties() -> Optional[list[str]]:
    raw = os.getenv("CLERK_AUTHORIZED_PARTIES", "")
    parties = [p.strip() for p in raw.split(",") if p.strip()]
    return parties or None


def is_configured() -> bool:
    """True iff at least one auth mode is configured."""
    return _clerk_secret() is not None or _expected_static_token() is not None


# ----- Clerk JWT verification -----------------------------------------------


def _looks_like_jwt(token: str) -> bool:
    """A Clerk session JWT has exactly three dot-separated base64url segments.

    Static tokens generated by `secrets.token_urlsafe()` don't contain dots,
    so this heuristic cleanly distinguishes the two on the wire.
    """
    parts = token.split(".")
    return len(parts) == 3 and all(p for p in parts)


async def _verify_clerk_jwt(request: Request) -> Optional[str]:
    """Verify a Clerk session token from the request's Authorization header.

    Returns the Clerk user_id (the JWT's `sub` claim) on success.
    Raises HTTPException(401) when the SDK rejects the token.
    Returns None when the SDK is unavailable or the request has no bearer.
    """
    secret = _clerk_secret()
    if secret is None:
        return None

    # Lazy import so module load doesn't require the SDK when Clerk is unused.
    try:
        from clerk_backend_api import (
            AuthenticateRequestOptions,
            authenticate_request_async,
        )
    except ImportError as e:
        logger.error(
            "clerk-backend-api not installed despite CLERK_SECRET_KEY set: %s. "
            "Run `pip install -e \".[dev]\"` in backend/.",
            e,
        )
        return None

    options = AuthenticateRequestOptions(
        secret_key=secret,
        authorized_parties=_authorized_parties(),
    )

    try:
        state = await authenticate_request_async(request, options)
    except Exception as e:  # noqa: BLE001 -- SDK can raise various exceptions
        logger.warning(
            "clerk authenticate_request raised %s: %s",
            type(e).__name__,
            e,
        )
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="invalid session token",
            headers={"WWW-Authenticate": "Bearer"},
        ) from e

    if not state.is_signed_in:
        reason = getattr(state, "reason", "unknown")
        logger.info("clerk session not signed in: reason=%s", reason)
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="not signed in",
            headers={"WWW-Authenticate": "Bearer"},
        )

    payload = state.payload or {}
    user_id = payload.get("sub")
    if not user_id:
        # Valid JWT but no subject -- shouldn't happen for Clerk session tokens.
        logger.warning("clerk JWT verified but missing 'sub' claim")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="session token missing user identity",
            headers={"WWW-Authenticate": "Bearer"},
        )
    return user_id


# ----- The FastAPI dependency ------------------------------------------------


async def require_token(
    request: Request,
    authorization: Optional[str] = Header(default=None),
) -> str:
    """Verify Clerk JWT or static bearer; return a user-id-like string.

    Returns:
      - The Clerk user_id (e.g. "user_2abc...") when a Clerk session verifies.
      - "shared-token" when the static SHARPER_API_TOKEN matches.
      - "anonymous-dev" when no auth is configured (loopback-only).

    Raises HTTPException(401) when auth is configured but the request fails it.
    """
    clerk_secret = _clerk_secret()
    static_token = _expected_static_token()

    # Mode D: nothing configured -> dev pass-through.
    if clerk_secret is None and static_token is None:
        return "anonymous-dev"

    # Extract the bearer token (if any) for shape inspection.
    presented = ""
    if authorization and authorization.startswith("Bearer "):
        presented = authorization.removeprefix("Bearer ").strip()

    # If Clerk is configured AND the bearer looks like a JWT, try Clerk first.
    # If verification fails AND static bearer isn't configured, propagate the
    # 401. If static bearer IS configured, we'll fall through and try it next.
    if clerk_secret is not None and presented and _looks_like_jwt(presented):
        try:
            user_id = await _verify_clerk_jwt(request)
        except HTTPException:
            if static_token is None:
                raise
            user_id = None
        if user_id is not None:
            return user_id

    # Static-bearer path.
    if static_token is None:
        # Clerk is the only configured mode and the request didn't carry a JWT.
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="missing Clerk session token",
            headers={"WWW-Authenticate": "Bearer"},
        )
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="missing Authorization: Bearer <token> header",
            headers={"WWW-Authenticate": "Bearer"},
        )
    if not secrets.compare_digest(presented, static_token):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="invalid token",
            headers={"WWW-Authenticate": "Bearer"},
        )
    return "shared-token"
